#!/bin/bash
#
# Run a build-script, from within the repository.
#

# Run make to build for all targets
echo "Build Started"

if make version=${{ github.event.release.tag_name }} ; then
    echo "Build Successful"
else
    echo "Build Failed"
    exit 1
fi