linters:
  fast: true
  disable-all: true
  enable:
    - revive
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - gosec
linters-settings:
  gofumpt:
    extra-rules: true
  gosec:
    excludes:
      - G107 # Url provided to HTTP request as taint input
      - G110 # Potential DoS vulnerability via decompression bomb
