title: gvm Documentation
description: A simple Go Version Management Tool with zero dependencies
theme: jekyll-theme-primer

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default
