title: gvm
description: A simple Go Version Management Tool with zero dependencies
theme: jekyll-theme-primer

repository: lokesh-balla/gvm

header_pages:
  - index.md
  - commands/index.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default
